#开发和生产环节隔离spring:
spring:
  profiles:
    active: dev
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/dev/*.xml,classpath*:mapper/admin/*.xml

